package service;

import model.Skill;
import model.Trainee;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.List;

/**
 * Handles portfolio export for trainees.
 *
 * Design intent:
 * - Keep file I/O logic outside UI classes (`TraineeDashboard`).
 * - Make export behavior reusable from GUI, tests, and future APIs.
 * - Produce a deterministic, readable text file representation of trainee progress.
 */
public class PortfolioExporter {

    /**
     * Exports the trainee portfolio into a timestamped text file in the current
     * working directory.
     *
     * @param trainee the trainee whose portfolio should be exported
     * @param skills  the skill list to include in the file
     * @return absolute path to the generated export file
     * @throws IOException if the file cannot be written
     */
    public Path exportToTextFile(Trainee trainee, List<Skill> skills) throws IOException {
        if (trainee == null) {
            throw new IllegalArgumentException("Trainee cannot be null");
        }
        if (skills == null) {
            throw new IllegalArgumentException("Skills list cannot be null");
        }

        String safeName = trainee.getName().trim().replaceAll("\\s+", "_");
        String fileName = "portfolio_" + safeName + "_" + LocalDate.now() + ".txt";
        Path outputPath = Path.of(fileName).toAbsolutePath();

        try (BufferedWriter writer = Files.newBufferedWriter(outputPath, StandardCharsets.UTF_8)) {
            writer.write("=== SkillBridge Digital Portfolio ===");
            writer.newLine();
            writer.newLine();
            writer.write("Name     : " + trainee.getName());
            writer.newLine();
            writer.write("Email    : " + trainee.getEmail());
            writer.newLine();
            writer.write("Date     : " + LocalDate.now());
            writer.newLine();
            writer.write("Progress : " + trainee.getCompletionPercent() + "%");
            writer.newLine();
            writer.write("Certified: " + (trainee.isCertified() ? "YES" : "Not yet"));
            writer.newLine();
            writer.newLine();
            writer.write("--- Skills ---");
            writer.newLine();

            for (Skill skill : skills) {
                writer.write(String.format("[%s] %s (%s)",
                        skill.isCompleted() ? "x" : " ",
                        skill.getSkillName(),
                        skill.getLevel().name()));
                writer.newLine();
            }

            writer.newLine();
            writer.write("Generated by SkillBridge");
            writer.newLine();
        }

        return outputPath;
    }
}
